# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI Pipeline

on:
  push:
    branches:
      - CI_test
  pull_request:
    branches:
      - CI_test

jobs:
  backend:
    name: Backend Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4   # Updated to v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4  # Updated to v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4  # Updated to v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('backend/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Make Maven wrapper executable
        run: chmod +x mvnw
        working-directory: backend

      - name: Build Backend with Maven
        run: ./mvnw clean install
        working-directory: backend

      - name: Run Backend Tests
        run: ./mvnw test
        working-directory: backend

      - name: Package the Backend application
        if: success()
        run: ./mvnw package
        working-directory: backend

      - name: Archive Backend JAR
        if: success()
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: spring-boot-backend-app
          path: backend/target/*.jar

