name: Full Stack Deploy Pipeline for main

on:
  push:
    branches:
      - main

jobs:
  # Job 1: Deploy Backend
  deploy-backend:
    name: Build and Deploy Backend
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    # Set up JDK 17 for the backend
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Build the backend with Maven to generate the jar file
    - name: Build Backend with Maven
      run: mvn clean package --file Back-end/pom.xml

    # Build Docker image for backend and push to Docker Hub
    - name: Build and push Docker image for Backend
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker build -f Back-end/Dockerfile -t backend:${{ github.sha }} Back-end
        docker tag backend:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.sha }}

    # Deploy the Backend Docker container
    - name: Deploy Backend Docker container
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.sha }}
    # Stops the older running containers.
        docker stop backend || true
        docker rm backend || true
        docker run -d --name backend -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.sha }}

  # Job 2: Deploy Frontend
  deploy-frontend:
    name: Build and Deploy Frontend
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    # Set up Node.js for the front-end build
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Install dependencies and build the front-end React app
    - name: Install and Build Frontend
      run: |
        cd front-end
        npm install --legacy-peer-deps
        npm run build

    # Build Docker image for frontend and push to Docker Hub
    - name: Build and push Docker image for Frontend
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker build -f front-end/Dockerfile -t frontend:${{ github.sha }} front-end
        docker tag frontend:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }}

    # Deploy the Frontend Docker container
    - name: Deploy Frontend Docker container
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }}
    # Stops the older running containers.
        docker stop frontend || true
        docker rm frontend || true
        docker run -d --name frontend -p 80:80 ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }}
